// Mocks generated by Mockito 5.4.4 from annotations
// in exchange_rates/test/src/features/currency/data/data_sources/currency_exchange_rate_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:exchange_rates/src/core/network/web_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WebService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebService extends _i1.Mock implements _i2.WebService {
  MockWebService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> getRequest({
    required String? path,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> postRequest({
    required String? path,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postRequest,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #data: data,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> putRequest({
    required String? path,
    Map<String, dynamic>? queryParameters,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putRequest,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #data: data,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> deleteRequest({
    required String? path,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRequest,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
